version: '3'
services:
  elasticsearch:
    container_name: elk_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

  logstash:
    container_name: elk_logstash
    image: docker.elastic.co/logstash/logstash:7.14.0
    volumes:
      - /root/elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044
    depends_on:
      - elasticsearch

  kibana:
    container_name: elk_kibana
    image: docker.elastic.co/kibana/kibana:7.14.0
    volumes:
      - /root/elk/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  filebeat:
    container_name: elk_filebeat
    image: docker.elastic.co/beats/filebeat:7.14.0
    user: root
    volumes:
      - /root/elk/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: ["-e"]
    depends_on:
      - elasticsearch
